version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: employeesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../infra/terraform/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ../backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: employeesdb
      DB_USER: postgres
      DB_PASSWORD: postgres
    expose:
      - "8000"  
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:8000"  
    depends_on:
      - backend

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - proxy
