name: Pipeline cd-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get backend secret (staging)
        run: |
          ENV_VALUE=$(az keyvault secret show \
            --vault-name kv-sosso-devops-ci-cd \
            --name backend-env \
            --query value -o tsv)

          az webapp config appsettings set \
            --name backend-staging \
            --resource-group RG-TP \
            --settings BACKEND_ENV=$ENV_VALUE

      - name: Build Docker image
        working-directory: backend
        run: docker build -t backend:latest .

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login myacr.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Tag & push backend image
        run: |
          docker tag backend:latest myacr.azurecr.io/backend:latest
          docker push myacr.azurecr.io/backend:latest

      - name: Deploy container to Azure (staging)
        run: |
          az webapp create --name backend-staging \
                          --resource-group RG-TP \
                          --plan backend-plan \
                          --deployment-container-image-name myacr.azurecr.io/backend:latest

  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get backend secret (production)
        run: |
          ENV_VALUE=$(az keyvault secret show \
            --vault-name kv-sosso-devops-ci-cd \
            --name backend-env-prod \
            --query value -o tsv)

          az webapp config appsettings set \
            --name backend-prod \
            --resource-group RG-TP \
            --settings BACKEND_ENV=$ENV_VALUE

      - name: Build Docker image
        working-directory: backend
        run: docker build -t backend:latest .

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login myacr.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Tag & push backend image
        run: |
          docker tag backend:latest myacr.azurecr.io/backend:latest
          docker push myacr.azurecr.io/backend:latest

      - name: Deploy container to Azure (production)
        run: |
          az webapp create --name backend-prod \
                          --resource-group RG-TP \
                          --plan backend-plan \
                          --deployment-container-image-name myacr.azurecr.io/backend:latest
