name: Pipeline cd-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build, tag & push image to ACR
        working-directory: backend
        run: |
          docker build -t backend:latest .
          docker tag backend:latest acrdevopssosso.azurecr.io/backend:latest
          echo ${{ secrets.ACR_PASSWORD }} | docker login acrdevopssosso.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin
          docker push acrdevopssosso.azurecr.io/backend:latest

      - name: Configure container image (MSI only)
        run: |
          az webapp config container set \
            --name sosso-backend-staging \
            --resource-group rg-sosso-devops-ci-cd \
            --docker-custom-image-name acrdevopssosso.azurecr.io/backend:latest \
            --docker-registry-server-url https://acrdevopssosso.azurecr.io

      - name: Inject BACKEND_ENV from Key Vault
        run: |
          az webapp config appsettings set \
            --name sosso-backend-staging \
            --resource-group rg-sosso-devops-ci-cd \
            --settings BACKEND_ENV="@Microsoft.KeyVault(SecretUri=https://kv-sosso-devops-ci-cd.vault.azure.net/secrets/backend-env/)"

      - name: Inject DB_PASSWORD from Key Vault (exemple supplémentaire)
        run: |
          az webapp config appsettings set \
            --name sosso-backend-staging \
            --resource-group rg-sosso-devops-ci-cd \
            --settings DB_PASSWORD="@Microsoft.KeyVault(SecretUri=https://kv-sosso-devops-ci-cd.vault.azure.net/secrets/db-password/)"

      - name: Restart Web App to apply new image + settings
        run: |
          az webapp restart \
            --name sosso-backend-staging \
            --resource-group rg-sosso-devops-ci-cd
