name: Pipeline cd-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        working-directory: backend
        run: docker build -t backend:latest .

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login acrdevopssosso.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Tag & push backend image
        run: |
          docker tag backend:latest acrdevopssosso.azurecr.io/backend:latest
          docker push acrdevopssosso.azurecr.io/backend:latest

      - name: Configure container image (staging)
        run: |
          az webapp config container set \
            --name sosso-backend-staging \
            --resource-group rg-sosso-devops-ci-cd \
            --container-image-name acrdevopssosso.azurecr.io/backend:latest \
            --container-registry-url https://acrdevopssosso.azurecr.io \
            --container-registry-user ${{ secrets.ACR_USERNAME }} \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}

      - name: Inject BACKEND_ENV into Azure Web App (staging)
        run: |
          ENV_VALUE=$(az keyvault secret show \
            --vault-name kv-sosso-devops-ci-cd \
            --name backend-env \
            --query value -o tsv)

          az webapp config appsettings set \
            --name sosso-backend-staging \
            --resource-group rg-sosso-devops-ci-cd \
            --settings BACKEND_ENV=$ENV_VALUE

  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        working-directory: backend
        run: docker build -t backend:latest .

      - name: Login to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login acrdevopssosso.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Tag & push backend image
        run: |
          docker tag backend:latest acrdevopssosso.azurecr.io/backend:latest
          docker push acrdevopssosso.azurecr.io/backend:latest

      - name: Configure container image (production)
        run: |
          az webapp config container set \
            --name backend-prod \
            --resource-group rg-sosso-devops-ci-cd \
            --container-image-name acrdevopssosso.azurecr.io/backend:latest

      - name: Inject BACKEND_ENV into Azure Web App (production)
        run: |
          ENV_VALUE=$(az keyvault secret show \
            --vault-name kv-sosso-devops-ci-cd \
            --name backend-env-prod \
            --query value -o tsv)

          az webapp config appsettings set \
            --name backend-prod \
            --resource-group rg-sosso-devops-ci-cd \
            --settings BACKEND_ENV=$ENV_VALUE
