name: CI Backend FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: backend
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r backend/requirements.txt
        pip install flake8 pytest pytest-cov

    - name: Lint with Flake8
      run: flake8 backend

    - name: Run tests with coverage
      run: pytest backend/tests --cov=backend --cov-report=term-missing

    - name: SonarCloud analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=sofiane1234_projet-devops-ci-cd \
          -Dsonar.organization=sofiane1234 \
          -Dsonar.sources=backend \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN

    - name: Build and push Docker image
      run: |
        docker build -t acrdevopssosso.azurecr.io/backend:${{ github.sha }} backend/
        echo "$ACR_PASSWORD" | docker login acrdevopssosso.azurecr.io -u "$ACR_USERNAME" --password-stdin
        docker push acrdevopssosso.azurecr.io/backend:${{ github.sha }}
